version: 2

jobs:
    build:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - run:
                  name: Install dependencies
                  command: npm ci
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - /home/circleci/.npm
            - run:
                  name: Run tests
                  command: npm test
    deploy:
            docker:
                - image: alpine
            branches:
                only:
                    - master
                    - master-ci
            - setup_remote_docker:
                  docker_layer_caching: true
            - run:
                    TAG=0.1.$CIRCLE_BUILD_NUM
                    docker build -t jallier/ezybucks_frontend:$TAG .
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push jallier/ezybucks_frontend:$TAG
