version: 2

jobs:
    build:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - run:
                  name: Install dependencies
                  command: npm ci
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - /home/circleci/.npm
            - run:
                  name: Run tests
                  command: npm test
    deploy:
        docker:
            - image: docker:17.05.0-ce-git
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - restore_cache:
                keys:
                    - v1-{{ .Branch }}
                paths:
                    - /caches/app.tar
            - run:
                name: Load Docker image layer cache
                command: |
                    set +o pipefail
                    docker load -i /caches/app.tar | true
            - run:
                name: Build docker image
                command: |
                  TAG=0.1.$CIRCLE_BUILD_NUM 
                  docker build -t jallier/ezybucks_frontend:$TAG --cache-from=app . 
            - run:
                name: Save Docker image layer cache
                command: |
                    mkdir -p /caches
                    docker save -o /caches/app.tar app
            - save_cache:
                key: v1-{{ .Branch }}-{{ epoch }}
                paths:
                  - /caches/app.tar
            - deploy:
                name: Push container to repo
                command: |
                    if [ "${CIRCLE_BRANCH}" == 'master']; then
                        TAG=0.1.$CIRCLE_BUILD_NUM docker build -t
                        docker login -u $DOCKER_USER -p $DOCKER_PASS 
                        docker push jallier/ezybucks_frontend:$TAG
                    fi
workflows:
    version: 2
    workflow:
        jobs:
            - build
            - deploy:
                  requires:
                      - build
                  filters:
                      branches:
                          only:
                              - master
                              - master-ci
